Repository hot-gamza/loveloveshot-spring-boot, pull requests merged in 2023-09, with the labels that each got.

#6 setting: db연동 완료
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙ Setting

#11 [FEATURE] - {FEEDBACK} 피드백 엔티티 설계
  src/main/java/com/loveloveshot/feedback/command/domain/aggregate/entity/Feedback.java
Labels: ✨ Feature, ⚙ Setting

#12 [FEATURE] - {FEEDBACK} 피드백 서비스 테스트 및 기능 구현
  src/main/java/com/loveloveshot/common/annotation/DomainService.java
  src/main/java/com/loveloveshot/common/annotation/InfraService.java
  src/main/java/com/loveloveshot/common/annotation/test.java
  src/main/java/com/loveloveshot/feedback/command/application/dto/request/FeedbackRequest.java
  src/main/java/com/loveloveshot/feedback/command/application/dto/response/FeedbackResponse.java
  src/main/java/com/loveloveshot/feedback/command/application/dto/test.java
  src/main/java/com/loveloveshot/feedback/command/application/service/FeedbackCommandService.java
  src/main/java/com/loveloveshot/feedback/command/application/service/test.java
  src/main/java/com/loveloveshot/feedback/command/domain/aggregate/entity/test.java
  src/main/java/com/loveloveshot/feedback/command/domain/aggregate/vo/FeedbackWriterVO.java
  src/main/java/com/loveloveshot/feedback/command/domain/aggregate/vo/test.java
  src/main/java/com/loveloveshot/feedback/command/domain/repository/FeedbackCommandRepository.java
  src/main/java/com/loveloveshot/feedback/command/domain/repository/test.java
  src/main/java/com/loveloveshot/feedback/command/infrastructure/repository/test.java
  src/main/java/com/loveloveshot/feedback/query/application/service/FeedbackQueryService.java
  src/main/java/com/loveloveshot/feedback/query/application/service/test.java
  src/main/java/com/loveloveshot/feedback/query/domain/repository/FeedbackQueryRepository.java
  src/main/java/com/loveloveshot/feedback/query/infrastructure/repository/test.java
  src/test/java/com/loveloveshot/feedback/command/application/controller/FeedbackCommandControllerTest.java
  src/test/java/com/loveloveshot/feedback/command/application/service/FeedbackCommandServiceTest.java
  src/test/java/com/loveloveshot/feedback/command/domain/service/FeedbackCommandDomainServiceTest.java
  src/test/java/com/loveloveshot/feedback/query/application/controller/FeedbackQueryControllerTest.java
  src/test/java/com/loveloveshot/feedback/query/application/service/FeedbackQueryServiceTest.java
Labels: 🎯 Test, ✨ Feature, ⚙ Setting

#15 [FEATURE] - {FEEDBACK} 공용 ApiResponse, 피드백 컨트롤러 테스트 및 기능 구현
  src/main/java/com/loveloveshot/common/response/ApiResponse.java
  src/main/java/com/loveloveshot/common/response/enumtype/ApiStatus.java
  src/main/java/com/loveloveshot/feedback/command/application/controller/FeedbackCommandController.java
  src/main/java/com/loveloveshot/feedback/command/application/controller/test.java
  src/main/java/com/loveloveshot/feedback/command/application/service/FeedbackCommandService.java
  src/test/java/com/loveloveshot/feedback/command/application/controller/FeedbackCommandControllerTest.java
  src/test/java/com/loveloveshot/feedback/command/application/service/FeedbackCommandServiceTest.java
Labels: 🎯 Test, ✨ Feature, ⚙ Setting

#17 [Feature] - {IMAGE} 이미지 업로드 기능
  .gitignore
  src/main/java/com/loveloveshot/image/command/application/controller/ImageCommandController.java
  src/main/java/com/loveloveshot/image/command/application/controller/test.java
  src/main/java/com/loveloveshot/image/command/application/dto/RequestImageListDTO.java
  src/main/java/com/loveloveshot/image/command/application/dto/RequestSingleImageDTO.java
  src/main/java/com/loveloveshot/image/command/application/dto/test.java
  src/main/java/com/loveloveshot/image/command/application/service/ImageCommandService.java
  src/main/java/com/loveloveshot/image/command/application/service/test.java
  src/main/java/com/loveloveshot/image/command/domain/aggregate/entity/Image.java
  src/main/java/com/loveloveshot/image/command/domain/aggregate/entity/test.java
  src/main/java/com/loveloveshot/image/command/domain/aggregate/vo/UserVO.java
  src/main/java/com/loveloveshot/image/command/domain/aggregate/vo/test.java
  src/main/java/com/loveloveshot/image/command/domain/repository/ImageCommandRepository.java
  src/main/java/com/loveloveshot/image/command/domain/repository/test.java
  src/main/java/com/loveloveshot/image/command/domain/service/ImageCommandDomainService.java
  src/main/java/com/loveloveshot/image/command/domain/service/test.java
  src/main/java/com/loveloveshot/image/command/infrastructure/service/ImageCommandInfraService.java
  src/main/java/com/loveloveshot/image/command/infrastructure/service/test.java
  src/main/resources/static/index.html
Labels: ✨ Feature, ⚙ Setting

#19 [FEATURE] - {Log} Log4j2 세팅 및 Logging 기능 구현
  build.gradle
  src/main/resources/log4j2.yml
  src/test/java/com/loveloveshot/LoggingTest.java
Labels: 🎯 Test, ✨ Feature, ⚙ Setting

#22 [Feature] - {IMAGE} 이미지 컨트롤러 및 서비스 기능 추가
  src/main/java/com/loveloveshot/configuration/WebConfig.java
  src/main/java/com/loveloveshot/configuration/test.java
  src/main/java/com/loveloveshot/image/command/application/controller/ImageCommandController.java
  src/main/java/com/loveloveshot/image/command/application/dto/AIImageResponseDTO.java
  src/main/java/com/loveloveshot/image/command/application/dto/ImageListRequestDTO.java
  src/main/java/com/loveloveshot/image/command/application/dto/SingleImageRequestDTO.java
  src/main/java/com/loveloveshot/image/command/application/service/ImageCommandService.java
  src/main/java/com/loveloveshot/image/command/domain/service/ImageCommandDomainService.java
  src/main/java/com/loveloveshot/image/command/infrastructure/service/ImageCommandInfraService.java
  src/main/resources/static/properties/image.properties
  src/test/java/com/loveloveshot/feedback/command/application/service/FeedbackCommandServiceTest.java
Labels: 🔨 Refactor, ✨ Feature

#25 Create application.yml
  .github/workflows/gradle.yml
Labels: ⚙ Setting

#26 [FEATURE] - {Image} Infra Service 구현
  build.gradle
  src/main/java/com/loveloveshot/LoveloveshotApplication.java
  src/main/java/com/loveloveshot/image/command/application/controller/ImageCommandController.java
  src/main/java/com/loveloveshot/image/command/application/dto/ImagesDTO.java
  src/main/java/com/loveloveshot/image/command/application/dto/RequestImageListDTO.java
  src/main/java/com/loveloveshot/image/command/application/dto/RequestSingleImageDTO.java
  src/main/java/com/loveloveshot/image/command/application/service/ImageCommandService.java
  src/main/java/com/loveloveshot/image/command/domain/service/ImageCommandDomainService.java
  src/main/java/com/loveloveshot/image/command/infrastructure/service/HttpPostMultipart.java
  src/main/java/com/loveloveshot/image/command/infrastructure/service/ImageCommandInfraService.java
  src/test/java/com/loveloveshot/feedback/command/application/service/FeedbackCommandServiceTest.java
  src/test/java/com/loveloveshot/image/command/application/service/ImageCommandServiceTest.java
Labels: 📬 API, ✨ Feature

#27 [REFACTORING] - {IMAGE} AI 서버와 HTTP 통신 관련 리팩토링
  build.gradle
  src/main/java/com/loveloveshot/image/command/application/controller/ImageCommandController.java
  src/main/java/com/loveloveshot/image/command/application/dto/AiImageResponse.java
  src/main/java/com/loveloveshot/image/command/application/dto/ImageListRequest.java
  src/main/java/com/loveloveshot/image/command/application/dto/SingleImageRequest.java
  src/main/java/com/loveloveshot/image/command/application/service/ImageCommandService.java
  src/main/java/com/loveloveshot/image/command/domain/service/ImageCommandDomainService.java
  src/main/java/com/loveloveshot/image/command/infrastructure/service/ImageCommandInfraService.java
  src/main/resources/static/properties/image.properties
Labels: 🔨 Refactor, 📬 API, ✨ Feature, ⚙ Setting

#31 [BUGFIX] - {IMAGE} 클라이언트에서 결과 안 보이는 버그 해결
  build.gradle
  src/main/java/com/loveloveshot/configuration/WebClientConfig.java
  src/main/java/com/loveloveshot/image/command/application/controller/ImageCommandController.java
  src/main/java/com/loveloveshot/image/command/application/dto/ImageResponse.java
  src/main/java/com/loveloveshot/image/command/application/service/ImageCommandService.java
  src/main/java/com/loveloveshot/image/command/domain/service/ImageCommandDomainService.java
  src/main/java/com/loveloveshot/image/command/infrastructure/service/ImageCommandInfraService.java
Labels: 🔨 Refactor, 📬 API, 🐞 BugFix

#37 [FEATURE] - {IMAGE} 프리미엄 기능, 대기열 기능 추가
  src/main/java/com/loveloveshot/image/command/application/controller/ImageCommandController.java
  src/main/java/com/loveloveshot/image/command/application/dto/request/ImageRequest.java
  src/main/java/com/loveloveshot/image/command/application/dto/request/SaveRequest.java
  src/main/java/com/loveloveshot/image/command/application/dto/response/UploadResponse.java
  src/main/java/com/loveloveshot/image/command/application/service/ImageCommandService.java
  src/main/java/com/loveloveshot/image/command/application/service/ImageException.java
  src/main/java/com/loveloveshot/image/command/domain/aggregate/entity/AiImage.java
  src/main/java/com/loveloveshot/image/command/infrastructure/service/ImageCommandInfraService.java
  src/main/resources/static/index.html
Labels: 📬 API, ✨ Feature

#39 [Feature] - {OAUTH2} 소셜 로그인 구현
  build.gradle
  src/main/java/com/loveloveshot/LoveloveshotApplication.java
  src/main/java/com/loveloveshot/common/exception/ExceptionResponseHandler.java
  src/main/java/com/loveloveshot/common/exception/test.java
  src/main/java/com/loveloveshot/configuration/properties/AppProperties.java
  src/main/java/com/loveloveshot/configuration/properties/CorsProperties.java
  src/main/java/com/loveloveshot/configuration/security/JwtConfig.java
  src/main/java/com/loveloveshot/configuration/security/SecurityConfig.java
  src/main/java/com/loveloveshot/oauth/application/controller/AuthController.java
  src/main/java/com/loveloveshot/oauth/application/dto/handler/OAuth2AuthenticationFailHandler.java
  src/main/java/com/loveloveshot/oauth/application/dto/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/loveloveshot/oauth/application/dto/handler/TokenAccessDeniedHandler.java
  src/main/java/com/loveloveshot/oauth/application/dto/info/OAuth2UserInfo.java
  src/main/java/com/loveloveshot/oauth/application/dto/info/OAuth2UserInfoFactory.java
  src/main/java/com/loveloveshot/oauth/application/dto/info/impl/GoogleOAuth2UserInfo.java
  src/main/java/com/loveloveshot/oauth/application/dto/info/impl/KakaoOAuth2UserInfo.java
  src/main/java/com/loveloveshot/oauth/application/dto/info/impl/NaverOAuth2UserInfo.java
  src/main/java/com/loveloveshot/oauth/application/dto/request/AuthCommandRequest.java
  src/main/java/com/loveloveshot/oauth/application/service/CustomOAuth2UserService.java
  src/main/java/com/loveloveshot/oauth/application/service/CustomUserDetailsService.java
  src/main/java/com/loveloveshot/oauth/domain/aggregate/entity/UserPrincipal.java
  src/main/java/com/loveloveshot/oauth/domain/aggregate/enumType/RoleType.java
  src/main/java/com/loveloveshot/oauth/domain/aggregate/enumType/SocialType.java
  src/main/java/com/loveloveshot/oauth/domain/exception/OAuthProviderMissMatchException.java
  src/main/java/com/loveloveshot/oauth/domain/exception/RestAuthenticationEntryPoint.java
  src/main/java/com/loveloveshot/oauth/domain/exception/TokenValidFailedException.java
  src/main/java/com/loveloveshot/oauth/domain/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/loveloveshot/oauth/filter/TokenAuthenticationFilter.java
  src/main/java/com/loveloveshot/oauth/token/AuthToken.java
  src/main/java/com/loveloveshot/oauth/token/AuthTokenProvider.java
  src/main/java/com/loveloveshot/user/command/application/controller/UserCommandController.java
  src/main/java/com/loveloveshot/user/command/application/controller/test.java
  src/main/java/com/loveloveshot/user/command/application/dto/response/ApiResponseHeader.java
  src/main/java/com/loveloveshot/user/command/application/dto/test.java
  src/main/java/com/loveloveshot/user/command/application/service/UserCommandService.java
  src/main/java/com/loveloveshot/user/command/application/service/test.java
  src/main/java/com/loveloveshot/user/command/domain/aggregate/entity/BaseTimeEntity.java
  src/main/java/com/loveloveshot/user/command/domain/aggregate/entity/User.java
  src/main/java/com/loveloveshot/user/command/domain/aggregate/entity/test.java
  src/main/java/com/loveloveshot/user/command/domain/repository/UserRepository.java
  src/main/java/com/loveloveshot/user/command/domain/repository/test.java
  src/main/java/com/loveloveshot/utils/CookieUtil.java
  src/main/java/com/loveloveshot/utils/HeaderUtil.java
Labels: ✨ Feature

#40 [Feature] - {IMAGE} 사진첩 기능
  src/main/java/com/loveloveshot/image/command/application/dto/request/FindRequest.java
  src/main/java/com/loveloveshot/image/command/application/dto/request/SaveRequest.java
  src/main/java/com/loveloveshot/image/query/application/controller/ImageQueryController.java
  src/main/java/com/loveloveshot/image/query/application/service/ImageQueryService.java
  src/main/java/com/loveloveshot/image/query/domain/repository/ImageQueryRepository.java
  src/test/java/com/loveloveshot/image/query/application/service/ImageQueryServiceTests.java
Labels: 🎯 Test, ✨ Feature
